version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    environment:
      - APP_NAME=django
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery-worker
      - celery-beat

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  celery-worker:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-worker
    environment:
      - APP_NAME=celery-worker
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery-beat
    environment:
      - APP_NAME=celery-beat
    entrypoint: ./docker-entrypoint.sh
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery-worker
