version: '3'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery-worker
      - celery-beat

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  celery-worker:    
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A maskanib_test worker --loglevel=info
    container_name: celery-worker
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A maskanib_test beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    container_name: celery-beat
    volumes:
      - .:/app
    depends_on:
      - redis
