# Generated by Django 4.2.3 on 2023-07-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='lval30',
            field=models.CharField(max_length=40),
        ),
    ]
