# Generated by Django 4.2.3 on 2023-07-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_index_lval30'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexhistory',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='api.index', to_field='ins_code'),
        ),
    ]
