# Generated by Django 4.2.3 on 2023-07-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_indexhistory_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexhistory',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
